import './js/slider.js';
import './js/modal-script';
import './js/mobile-menu';
import './js/modal-buy';
import './js/modal-ingredients';
import './js/modal-made';
import './js/modal-locations';
import './js/modal-franchise';
import './js/video-close';